# This is a basic workflow to help you get started with Actions

name: dev_frontend_test

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
  workflow_dispatch:


jobs:
  FrontendTestDev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
          
      - name: Dependencies
        run: npm ci
        working-directory: frontend

      - name: Build
        run: npm run build
        env:
          REACT_APP_APIURL: ${{ secrets.REACT_APP_APIURL }}
        working-directory: frontend

      - name: Test
        run: npm run test
        working-directory: frontend